apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-oauth
spec:
  replicas: 0
  selector:
    matchLabels:
      app: msvc-oauth
  template:
    metadata:
      labels:
        app: msvc-oauth
    spec:
      containers:
        - image: osmago/oauth:latest
          name: msvc-oauth
          ports:
            - containerPort: 9000
          env:
            - name: LB_USUARIOS_URI
              valueFrom:
                configMapKeyRef:
                  name: msvc-usuarios
                  key: lb_usuarios_uri
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-oauth
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: msvc-oauth
  sessionAffinity: None
  type: LoadBalancer